# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from sys import _xoptions
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.sip import SIP_VERSION

class Ui_blackground(object):
    def setupUi(self, blackground):
        blackground.setObjectName("blackground")
        blackground.resize(215, 358)
        blackground.setStyleSheet("QWidget{\n"
"background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #a8ff90, stop: 1 #ffd5db\n"
"        );\n"
"color: white;\n"
"}")
        self.ans_box = QtWidgets.QLabel(blackground)
        self.ans_box.setGeometry(QtCore.QRect(10, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.ans_box.setFont(font)
        self.ans_box.setStyleSheet("QLabel{\n"
"  color: #333;\n"
"  border: 2px solid #555;\n"
"  border-radius: 20px;\n"
"  background: white;\n"
"  padding: 5px;\n"
"  min-height: 20px;\n"
"  min-width: 20px;\n"
"}\n"
"\n"
"")
        self.ans_box.setFrameShape(QtWidgets.QFrame.Box)
        self.ans_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ans_box.setText("")
        self.ans_box.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ans_box.setObjectName("ans_box")
        self.botton7 = QtWidgets.QPushButton(blackground, clicked= lambda: self.press("7"))
        self.botton7.setGeometry(QtCore.QRect(10, 110, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botton7.setFont(font)
        self.botton7.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.botton7.setCheckable(False)
        self.botton7.setObjectName("botton7")
        self.botton8 = QtWidgets.QPushButton(blackground, clicked= lambda: self.press("8"))
        self.botton8.setGeometry(QtCore.QRect(60, 110, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botton8.setFont(font)
        self.botton8.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.botton8.setCheckable(False)
        self.botton8.setObjectName("botton8")
        self.botton9 = QtWidgets.QPushButton(blackground, clicked= lambda: self.press("9"))
        self.botton9.setGeometry(QtCore.QRect(110, 110, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botton9.setFont(font)
        self.botton9.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.botton9.setCheckable(False)
        self.botton9.setObjectName("botton9")
        self.bottondivide = QtWidgets.QPushButton(blackground, clicked= lambda: self.simb("/"))
        self.bottondivide.setGeometry(QtCore.QRect(160, 110, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.bottondivide.setFont(font)
        self.bottondivide.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.bottondivide.setCheckable(False)
        self.bottondivide.setObjectName("bottondivide")
        self.botton6 = QtWidgets.QPushButton(blackground, clicked= lambda: self.press("6"))
        self.botton6.setGeometry(QtCore.QRect(110, 160, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botton6.setFont(font)
        self.botton6.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.botton6.setCheckable(False)
        self.botton6.setObjectName("botton6")
        self.bottonmutiply = QtWidgets.QPushButton(blackground, clicked= lambda: self.simb("*"))
        self.bottonmutiply.setGeometry(QtCore.QRect(160, 160, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.bottonmutiply.setFont(font)
        self.bottonmutiply.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.bottonmutiply.setCheckable(False)
        self.bottonmutiply.setObjectName("bottonmutiply")
        self.botton5 = QtWidgets.QPushButton(blackground, clicked= lambda: self.press("5"))
        self.botton5.setGeometry(QtCore.QRect(60, 160, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botton5.setFont(font)
        self.botton5.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.botton5.setCheckable(False)
        self.botton5.setObjectName("botton5")
        self.botton4 = QtWidgets.QPushButton(blackground, clicked= lambda: self.press("4"))
        self.botton4.setGeometry(QtCore.QRect(10, 160, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botton4.setFont(font)
        self.botton4.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.botton4.setCheckable(False)
        self.botton4.setObjectName("botton4")
        self.bottonpoint = QtWidgets.QPushButton(blackground, clicked= lambda: self.point())
        self.bottonpoint.setGeometry(QtCore.QRect(110, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.bottonpoint.setFont(font)
        self.bottonpoint.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.bottonpoint.setCheckable(False)
        self.bottonpoint.setObjectName("bottonpoint")
        self.botton3 = QtWidgets.QPushButton(blackground, clicked= lambda: self.press("3"))
        self.botton3.setGeometry(QtCore.QRect(110, 210, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botton3.setFont(font)
        self.botton3.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.botton3.setCheckable(False)
        self.botton3.setObjectName("botton3")
        self.bottonplus = QtWidgets.QPushButton(blackground, clicked= lambda: self.simb("+"))
        self.bottonplus.setGeometry(QtCore.QRect(160, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.bottonplus.setFont(font)
        self.bottonplus.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.bottonplus.setCheckable(False)
        self.bottonplus.setObjectName("bottonplus")
        self.botton0 = QtWidgets.QPushButton(blackground, clicked= lambda: self.press("0"))
        self.botton0.setGeometry(QtCore.QRect(60, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botton0.setFont(font)
        self.botton0.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.botton0.setCheckable(False)
        self.botton0.setObjectName("botton0")
        self.bottonminus = QtWidgets.QPushButton(blackground, clicked= lambda: self.simb("-"))
        self.bottonminus.setGeometry(QtCore.QRect(160, 210, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.bottonminus.setFont(font)
        self.bottonminus.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.bottonminus.setCheckable(False)
        self.bottonminus.setObjectName("bottonminus")
        self.bottonans = QtWidgets.QPushButton(blackground, clicked= lambda: self.calculate())
        self.bottonans.setGeometry(QtCore.QRect(110, 310, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.bottonans.setFont(font)
        self.bottonans.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.bottonans.setCheckable(False)
        self.bottonans.setObjectName("bottonans")
        self.botton2 = QtWidgets.QPushButton(blackground, clicked= lambda: self.press("2"))
        self.botton2.setGeometry(QtCore.QRect(60, 210, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botton2.setFont(font)
        self.botton2.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.botton2.setCheckable(False)
        self.botton2.setObjectName("botton2")
        self.botton1 = QtWidgets.QPushButton(blackground, clicked= lambda: self.press("1"))
        self.botton1.setGeometry(QtCore.QRect(10, 210, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.botton1.setFont(font)
        self.botton1.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.botton1.setCheckable(False)
        self.botton1.setObjectName("botton1")
        self.bottonCE = QtWidgets.QPushButton(blackground, clicked= lambda: self.clear_entry())
        self.bottonCE.setGeometry(QtCore.QRect(10, 310, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.bottonCE.setFont(font)
        self.bottonCE.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.bottonCE.setCheckable(False)
        self.bottonCE.setObjectName("bottonCE")
        self.bottonC = QtWidgets.QPushButton(blackground, clicked= lambda: self.clear())
        self.bottonC.setGeometry(QtCore.QRect(60, 310, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.bottonC.setFont(font)
        self.bottonC.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.bottonC.setCheckable(False)
        self.bottonC.setObjectName("bottonC")
        self.ans_label_2 = QtWidgets.QLabel(blackground)
        self.ans_label_2.setGeometry(QtCore.QRect(10, 60, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.ans_label_2.setFont(font)
        self.ans_label_2.setStyleSheet("QLabel{\n"
"  color: #333;\n"
"  border: 2px solid #555;\n"
"  border-radius: 20px;\n"
"  background: white;\n"
"  padding: 5px;\n"
"  min-height: 20px;\n"
"  min-width: 20px;\n"
"}\n"
"\n"
"")
        self.ans_label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.ans_label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ans_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ans_label_2.setObjectName("ans_label_2")
        self.bottonDel = QtWidgets.QPushButton(blackground, clicked= lambda: self.Del())
        self.bottonDel.setGeometry(QtCore.QRect(10, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.bottonDel.setFont(font)
        self.bottonDel.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: white;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.bottonDel.setCheckable(False)
        self.bottonDel.setObjectName("bottonDel")

        self.retranslateUi(blackground)
        QtCore.QMetaObject.connectSlotsByName(blackground)

    def retranslateUi(self, blackground):
        _translate = QtCore.QCoreApplication.translate
        blackground.setWindowTitle(_translate("blackground", "Calculator"))
        self.botton7.setText(_translate("blackground", "7"))
        self.botton8.setText(_translate("blackground", "8"))
        self.botton9.setText(_translate("blackground", "9"))
        self.bottondivide.setText(_translate("blackground", "/"))
        self.botton6.setText(_translate("blackground", "6"))
        self.bottonmutiply.setText(_translate("blackground", "x"))
        self.botton5.setText(_translate("blackground", "5"))
        self.botton4.setText(_translate("blackground", "4"))
        self.bottonpoint.setText(_translate("blackground", "."))
        self.botton3.setText(_translate("blackground", "3"))
        self.bottonplus.setText(_translate("blackground", "+"))
        self.botton0.setText(_translate("blackground", "0"))
        self.bottonminus.setText(_translate("blackground", "-"))
        self.bottonans.setText(_translate("blackground", "="))
        self.botton2.setText(_translate("blackground", "2"))
        self.botton1.setText(_translate("blackground", "1"))
        self.bottonCE.setText(_translate("blackground", "CE"))
        self.bottonC.setText(_translate("blackground", "C"))
        self.ans_label_2.setText(_translate("blackground", "0"))
        self.bottonDel.setText(_translate("blackground", "Del"))

    def press(self, pressed):
        if len(self.ans_label_2.text()) <= 8:
                if self.ans_label_2.text() == '.':
                        self.ans_label_2.setText(pressed)
                elif self.ans_label_2.text() == '0':
                        self.ans_label_2.setText(pressed)
                else:
                        self.ans_label_2.setText(f'{self.ans_label_2.text()}{pressed}')

    def point(self):
        screen = self.ans_label_2.text()
        if '.' in screen:
            pass
        else:
            self.ans_label_2.setText(f'{screen}.')

    def clear(self):
        self.ans_label_2.setText('0')
        self.ans_box.setText('')

    def simb(self,pressed):
        
        if self.ans_label_2.text() == '0' and self.ans_label_2.text() != '-':
            self.ans_label_2.setText('-')
        elif self.ans_label_2.text() == '0':
            pass
        elif self.ans_box.text() == '0':
            self.ans_box.setText(f'{self.ans_label_2.text()}{pressed}')
            self.ans_label_2.setText('0')
        else:
            self.ans_box.setText(f'{self.ans_box.text()}{self.ans_label_2.text()}{pressed}')
            self.ans_label_2.setText('0')

    def calculate(self):
        if self.ans_box.text() == '0':
            screen = self.ans_label_2.text()
        else:
            self.ans_box.setText(f'{self.ans_box.text()}{self.ans_label_2.text()}')
            screen = self.ans_box.text()
        try:
            ans = eval(screen)
            numbercounter = len(str(ans))
            convert = str(ans).replace('.','')
            y = str(ans)
            if numbercounter <= 9:
                self.ans_label_2.setText(str(ans))
                self.ans_box.setText(' ')
            elif float(ans) > 999999999 and float(ans)%1 == 0:
                self.ans_label_2.setText(convert[0] + '.' + convert[1:5] + 'E' + str(len(convert)-1))
                self.ans_box.setText(' ')
            elif float(ans) <= 999999999 and float(ans)>1:
                if y[9] == '.':
                        self.ans_label_2.setText(y[:9])
                        self.ans_box.setText(' ')
                elif int(y[8]) >= 5:
                        MMMM = str(ans).find('.')
                        SRR = int(convert[:8]) + 1
                        SSRR = str(SRR)
                        self.ans_label_2.setText(SSRR[:MMMM-1] + '.' + SSRR[MMMM:9])
                        self.ans_box.setText(' ')
                else:
                        self.ans_label_2.setText(y[:9])
                        self.ans_box.setText(' ')
            elif float(ans) < 1:
                m = convert
                XXX = y.find('E')
                for i in range(0,len(convert)):
                        if convert[i] != '0':
                                k = i
                                break
                if k == 0 and m[k+1:k+5] != '':
                        self.ans_label_2.setText(m[k] + '.' + m[k+1:k+3] + 'E' + '-' + y[XXX:])
                        self.ans_box.setText(' ')
                elif k == 0:
                        self.ans_label_2.setText(m[k] + m[k+1:k+3] + 'E' + '-' + y[XXX:])
                        self.ans_box.setText(' ')
                elif m[k+1:k+5] != '':
                        self.ans_label_2.setText(m[k] + '.' + m[k+1:k+3] + 'E' + '-' + str(k))
                        self.ans_box.setText(' ')
                else:
                        self.ans_label_2.setText(m[k] + m[k+1:k+3] + 'E' + '-' + str(k))
        except:
            self.ans_label_2.setText('Error')
            self.ans_box.setText(' ')
            
    def Del(self):
        if self.ans_label_2.text() == '-':
                self.ans_label_2.setText('0')
        elif len(self.ans_label_2.text()) >1:
                DELELL = self.ans_label_2.text()
                self.ans_label_2.setText(DELELL[:-1])
        elif len(self.ans_label_2.text()) == 1:
                self.ans_label_2.setText('0')
        
    def clear_entry(self):
        self.ans_label_2.setText('0')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    blackground = QtWidgets.QWidget()
    ui = Ui_blackground()
    ui.setupUi(blackground)
    blackground.show()
    sys.exit(app.exec_())